var mockUserData = [{
    "id": 282621394,
    "profile_image_url_https": "https:\/\/si0.twimg.com\/profile_images\/1373858432\/153581a_2_normal.jpg",
    "profile_background_image_url_https": "https:\/\/si0.twimg.com\/images\/themes\/theme14\/bg.gif",
    "friends_count": 41,
    "location": "Kansas City, MO",
    "default_profile_image": false,
    "profile_use_background_image": true,
    "profile_text_color": "333333",
    "favourites_count": 0,
    "lang": "en",
    "utc_offset": -21600,
    "profile_image_url": "http:\/\/a0.twimg.com\/profile_images\/1373858432\/153581a_2_normal.jpg",
    "name": "Kyle Carlson",
    "followers_count": 36,
    "profile_sidebar_border_color": "eeeeee",
    "id_str": "282621394",
    "protected": false,
    "profile_background_tile": true,
    "default_profile": false,
    "profile_sidebar_fill_color": "efefef",
    "following": null,
    "description": "Technology buff, Boglehead, atheist, web strategist @VossVisuals, ecommerce specialist, & world traveler who loves to eat sushi!",
    "notifications": null,
    "profile_background_color": "131516",
    "listed_count": 0,
    "contributors_enabled": false,
    "url": null,
    "created_at": "Fri Apr 15 15:26:50 +0000 2011",
    "geo_enabled": false,
    "verified": false,
    "status": {
        "geo": null,
        "in_reply_to_status_id": 197176153298055171,
        "in_reply_to_status_id_str": "197176153298055171",
        "truncated": false,
        "in_reply_to_user_id_str": "201891476",
        "coordinates": null,
        "place": null,
        "retweeted": false,
        "in_reply_to_screen_name": "danielmetdesign",
        "contributors": null,
        "source": "web",
        "id_str": "197372876192616448",
        "in_reply_to_user_id": 201891476,
        "id": 197372876192616448,
        "created_at": "Tue May 01 17:12:15 +0000 2012",
        "retweet_count": 0,
        "favorited": false,
        "text": "@danielmetdesign When does that new job start?"
    },
    "profile_background_image_url": "http:\/\/a0.twimg.com\/images\/themes\/theme14\/bg.gif",
    "is_translator": false,
    "show_all_inline_media": false,
    "profile_link_color": "009999",
    "statuses_count": 72,
    "screen_name": "kyletcarlson",
    "follow_request_sent": null,
    "time_zone": "Central Time (US & Canada)"
}, {
    "id": 21886850,
    "geo_enabled": true,
    "location": "Kansas",
    "verified": false,
    "profile_background_image_url": "http:\/\/a0.twimg.com\/profile_background_images\/61753002\/twitter-bg.png",
    "is_translator": false,
    "show_all_inline_media": false,
    "follow_request_sent": null,
    "time_zone": "Central Time (US & Canada)",
    "profile_link_color": "c89d00",
    "statuses_count": 656,
    "lang": "en",
    "utc_offset": -21600,
    "profile_image_url_https": "https:\/\/si0.twimg.com\/profile_images\/1244193500\/1297697266673_normal.png",
    "profile_background_image_url_https": "https:\/\/si0.twimg.com\/profile_background_images\/61753002\/twitter-bg.png",
    "friends_count": 146,
    "name": "Russell Madsen",
    "default_profile_image": false,
    "profile_use_background_image": true,
    "profile_text_color": "222222",
    "favourites_count": 256,
    "protected": false,
    "profile_image_url": "http:\/\/a0.twimg.com\/profile_images\/1244193500\/1297697266673_normal.png",
    "followers_count": 97,
    "profile_sidebar_border_color": "febf01",
    "id_str": "21886850",
    "following": null,
    "description": "web developer, disc golfer, renaissance man",
    "notifications": null,
    "profile_background_tile": false,
    "default_profile": false,
    "profile_sidebar_fill_color": "555555",
    "url": "http:\/\/www.madsendev.com",
    "created_at": "Wed Feb 25 16:54:45 +0000 2009",
    "status": {
        "geo": null,
        "truncated": false,
        "in_reply_to_user_id_str": "384644477",
        "retweeted": false,
        "coordinates": null,
        "in_reply_to_screen_name": "DaisyAPI",
        "place": null,
        "contributors": null,
        "id_str": "197021597834559488",
        "in_reply_to_user_id": 384644477,
        "retweet_count": 0,
        "favorited": false,
        "source": "\u003Ca href=\"http:\/\/itunes.apple.com\/us\/app\/twitter\/id409789998?mt=12\" rel=\"nofollow\"\u003ETwitter for Mac\u003C\/a\u003E",
        "in_reply_to_status_id": null,
        "id": 197021597834559488,
        "created_at": "Mon Apr 30 17:56:24 +0000 2012",
        "in_reply_to_status_id_str": null,
        "text": "@DaisyAPI - you have a very interesting product!  What an interesting replacement for my own imageMagick impementation"
    },
    "profile_background_color": "666666",
    "listed_count": 8,
    "contributors_enabled": false,
    "screen_name": "russellmadsen"
}, {
    "id": 14924164,
    "geo_enabled": false,
    "location": "kansas",
    "verified": false,
    "profile_background_image_url": "http:\/\/a0.twimg.com\/images\/themes\/theme1\/bg.png",
    "is_translator": false,
    "show_all_inline_media": false,
    "follow_request_sent": null,
    "time_zone": "Central Time (US & Canada)",
    "profile_link_color": "0084B4",
    "statuses_count": 213,
    "lang": "en",
    "utc_offset": -21600,
    "profile_image_url_https": "https:\/\/si0.twimg.com\/profile_images\/437601424\/david-headshot-90-117_normal.jpg",
    "profile_background_image_url_https": "https:\/\/si0.twimg.com\/images\/themes\/theme1\/bg.png",
    "friends_count": 102,
    "name": "davidmitchell",
    "default_profile_image": false,
    "profile_use_background_image": true,
    "profile_text_color": "333333",
    "favourites_count": 4,
    "protected": false,
    "profile_image_url": "http:\/\/a0.twimg.com\/profile_images\/437601424\/david-headshot-90-117_normal.jpg",
    "followers_count": 140,
    "profile_sidebar_border_color": "C0DEED",
    "id_str": "14924164",
    "following": null,
    "description": "",
    "notifications": null,
    "profile_background_tile": false,
    "default_profile": true,
    "profile_sidebar_fill_color": "DDEEF6",
    "url": "http:\/\/www.withaguide.com",
    "created_at": "Tue May 27 19:01:40 +0000 2008",
    "status": {
        "geo": null,
        "truncated": false,
        "in_reply_to_user_id_str": "17522606",
        "retweeted": false,
        "coordinates": null,
        "in_reply_to_screen_name": "mboomershine",
        "place": null,
        "contributors": null,
        "id_str": "191667377329545216",
        "in_reply_to_user_id": 17522606,
        "retweet_count": 0,
        "favorited": false,
        "source": "\u003Ca href=\"http:\/\/twitter.com\/#!\/download\/iphone\" rel=\"nofollow\"\u003ETwitter for iPhone\u003C\/a\u003E",
        "in_reply_to_status_id": 191576291185655808,
        "id": 191667377329545216,
        "created_at": "Sun Apr 15 23:20:38 +0000 2012",
        "in_reply_to_status_id_str": "191576291185655808",
        "text": "@mboomershine tdd only feels weird the first few times. Then you always start with tests. Sounds like you are having fun!"
    },
    "profile_background_color": "C0DEED",
    "listed_count": 7,
    "contributors_enabled": false,
    "screen_name": "davidmitchell"
}, {
    "id": 102291769,
    "geo_enabled": false,
    "location": "Kansas City",
    "verified": false,
    "profile_background_image_url": "http:\/\/a0.twimg.com\/images\/themes\/theme13\/bg.gif",
    "is_translator": false,
    "show_all_inline_media": false,
    "follow_request_sent": false,
    "time_zone": "Central Time (US & Canada)",
    "profile_link_color": "93A644",
    "statuses_count": 682,
    "lang": "en",
    "utc_offset": -21600,
    "profile_image_url_https": "https:\/\/si0.twimg.com\/profile_images\/1154678488\/Lighthouse_normal.jpg",
    "profile_background_image_url_https": "https:\/\/si0.twimg.com\/images\/themes\/theme13\/bg.gif",
    "friends_count": 260,
    "name": "Iris James ",
    "default_profile_image": false,
    "profile_use_background_image": true,
    "profile_text_color": "333333",
    "favourites_count": 1,
    "protected": false,
    "profile_image_url": "http:\/\/a0.twimg.com\/profile_images\/1154678488\/Lighthouse_normal.jpg",
    "followers_count": 88,
    "profile_sidebar_border_color": "eeeeee",
    "id_str": "102291769",
    "following": false,
    "description": "Technology Head Hunter aka The Direct-Hire Gal",
    "notifications": false,
    "profile_background_tile": false,
    "default_profile": false,
    "profile_sidebar_fill_color": "ffffff",
    "url": "http:\/\/www.altekkc.com",
    "created_at": "Wed Jan 06 06:19:06 +0000 2010",
    "status": {
        "geo": null,
        "truncated": false,
        "in_reply_to_user_id_str": null,
        "retweeted": false,
        "coordinates": null,
        "in_reply_to_screen_name": null,
        "place": null,
        "possibly_sensitive": false,
        "contributors": null,
        "id_str": "196036948983418880",
        "in_reply_to_user_id": null,
        "retweet_count": 0,
        "favorited": false,
        "source": "\u003Ca href=\"http:\/\/twitter.com\/tweetbutton\" rel=\"nofollow\"\u003ETweet Button\u003C\/a\u003E",
        "in_reply_to_status_id": null,
        "id": 196036948983418880,
        "created_at": "Sat Apr 28 00:43:45 +0000 2012",
        "in_reply_to_status_id_str": null,
        "text": ".NET Systems Programmer\/ Systems Developer opportunities. Software + systems, hardware, device exp.  Direct-Hire. https:\/\/t.co\/JNvMWuyT"
    },
    "profile_background_color": "B2DFDA",
    "listed_count": 0,
    "contributors_enabled": false,
    "screen_name": "altekkc"
}, {
    "id": 14773485,
    "geo_enabled": false,
    "location": "Missouri",
    "verified": false,
    "profile_background_image_url": "http:\/\/a0.twimg.com\/profile_background_images\/3167000\/Black_cassette_tape.jpg",
    "is_translator": false,
    "show_all_inline_media": false,
    "follow_request_sent": null,
    "time_zone": "Central Time (US & Canada)",
    "profile_link_color": "a85e36",
    "statuses_count": 191,
    "lang": "en",
    "utc_offset": -21600,
    "profile_image_url_https": "https:\/\/si0.twimg.com\/profile_images\/60668053\/photo_normal.jpg",
    "profile_background_image_url_https": "https:\/\/si0.twimg.com\/profile_background_images\/3167000\/Black_cassette_tape.jpg",
    "friends_count": 103,
    "name": "lp",
    "default_profile_image": false,
    "profile_use_background_image": true,
    "profile_text_color": "4d4d4d",
    "favourites_count": 15,
    "protected": false,
    "profile_image_url": "http:\/\/a0.twimg.com\/profile_images\/60668053\/photo_normal.jpg",
    "followers_count": 23,
    "profile_sidebar_border_color": "C6E2EE",
    "id_str": "14773485",
    "following": null,
    "description": "i wanna baptize your money maker",
    "notifications": null,
    "profile_background_tile": false,
    "default_profile": false,
    "profile_sidebar_fill_color": "8a8a8a",
    "url": null,
    "created_at": "Wed May 14 14:19:15 +0000 2008",
    "status": {
        "geo": null,
        "truncated": false,
        "in_reply_to_user_id_str": "15429304",
        "retweeted": false,
        "coordinates": null,
        "in_reply_to_screen_name": "mel_haas",
        "place": null,
        "contributors": null,
        "id_str": "169943484348895233",
        "in_reply_to_user_id": 15429304,
        "retweet_count": 0,
        "favorited": false,
        "source": "web",
        "in_reply_to_status_id": 167507839789699073,
        "id": 169943484348895233,
        "created_at": "Thu Feb 16 00:37:38 +0000 2012",
        "in_reply_to_status_id_str": "167507839789699073",
        "text": "@mel_haas orly? need to look into this."
    },
    "profile_background_color": "ffffff",
    "listed_count": 1,
    "contributors_enabled": false,
    "screen_name": "chobixupdate"
}, {
    "id": 8488362,
    "geo_enabled": false,
    "location": "Kansas City",
    "verified": false,
    "profile_background_image_url": "http:\/\/a0.twimg.com\/profile_background_images\/149213738\/francisrupert2.gif",
    "is_translator": false,
    "show_all_inline_media": true,
    "follow_request_sent": null,
    "time_zone": "Central Time (US & Canada)",
    "profile_link_color": "5c0000",
    "statuses_count": 2427,
    "lang": "en",
    "utc_offset": -21600,
    "profile_image_url_https": "https:\/\/si0.twimg.com\/profile_images\/1677936355\/me-color_500x500_normal.jpg",
    "profile_background_image_url_https": "https:\/\/si0.twimg.com\/profile_background_images\/149213738\/francisrupert2.gif",
    "friends_count": 435,
    "name": "Francis C. Rupert",
    "default_profile_image": false,
    "profile_use_background_image": true,
    "profile_text_color": "5f604a",
    "favourites_count": 141,
    "protected": false,
    "profile_image_url": "http:\/\/a0.twimg.com\/profile_images\/1677936355\/me-color_500x500_normal.jpg",
    "followers_count": 592,
    "profile_sidebar_border_color": "fcb468",
    "id_str": "8488362",
    "following": null,
    "description": "UXer; formerly of the West coast, living in the Midwest, working for @eightshapes on the East coast.",
    "notifications": null,
    "profile_background_tile": true,
    "default_profile": false,
    "profile_sidebar_fill_color": "dad5ce",
    "url": "http:\/\/about.me\/francisrupert",
    "created_at": "Tue Aug 28 15:46:18 +0000 2007",
    "status": {
        "geo": null,
        "truncated": false,
        "in_reply_to_user_id_str": null,
        "retweeted": false,
        "coordinates": null,
        "in_reply_to_screen_name": null,
        "place": null,
        "contributors": null,
        "id_str": "196435311734177793",
        "in_reply_to_user_id": null,
        "retweet_count": 0,
        "favorited": false,
        "source": "\u003Ca href=\"http:\/\/twitter.com\/#!\/download\/iphone\" rel=\"nofollow\"\u003ETwitter for iPhone\u003C\/a\u003E",
        "in_reply_to_status_id": null,
        "id": 196435311734177793,
        "created_at": "Sun Apr 29 03:06:42 +0000 2012",
        "in_reply_to_status_id_str": null,
        "text": "Bryce Harper rockin the stirrups. Respect. #Nats"
    },
    "profile_background_color": "f4f2f0",
    "listed_count": 63,
    "contributors_enabled": false,
    "screen_name": "francisrupert"
}, {
    "id": 17240018,
    "geo_enabled": true,
    "location": "Kansas City, MO USA",
    "verified": false,
    "profile_background_image_url": "http:\/\/a0.twimg.com\/profile_background_images\/28538708\/wolf_bg.jpg",
    "is_translator": false,
    "show_all_inline_media": false,
    "follow_request_sent": null,
    "time_zone": "Mountain Time (US & Canada)",
    "profile_link_color": "FF0000",
    "statuses_count": 263,
    "lang": "en",
    "utc_offset": -25200,
    "profile_image_url_https": "https:\/\/si0.twimg.com\/profile_images\/799585913\/6772_1139967552132_1615737186_353359_6607262_n_normal.jpg",
    "profile_background_image_url_https": "https:\/\/si0.twimg.com\/profile_background_images\/28538708\/wolf_bg.jpg",
    "friends_count": 54,
    "name": "triomatt",
    "default_profile_image": false,
    "profile_use_background_image": true,
    "profile_text_color": "8d9496",
    "favourites_count": 2,
    "protected": false,
    "profile_image_url": "http:\/\/a0.twimg.com\/profile_images\/799585913\/6772_1139967552132_1615737186_353359_6607262_n_normal.jpg",
    "followers_count": 48,
    "profile_sidebar_border_color": "78118f",
    "id_str": "17240018",
    "following": null,
    "description": "Nordic CSSMonkey",
    "notifications": null,
    "profile_background_tile": true,
    "default_profile": false,
    "profile_sidebar_fill_color": "0d0c0d",
    "url": null,
    "created_at": "Fri Nov 07 22:07:01 +0000 2008",
    "status": {
        "geo": null,
        "truncated": false,
        "in_reply_to_user_id_str": null,
        "retweeted": false,
        "coordinates": null,
        "in_reply_to_screen_name": null,
        "place": null,
        "contributors": null,
        "id_str": "195896142922383360",
        "in_reply_to_user_id": null,
        "retweet_count": 0,
        "favorited": false,
        "source": "\u003Ca href=\"http:\/\/www.linkedin.com\/\" rel=\"nofollow\"\u003ELinkedIn\u003C\/a\u003E",
        "in_reply_to_status_id": null,
        "id": 195896142922383360,
        "created_at": "Fri Apr 27 15:24:14 +0000 2012",
        "in_reply_to_status_id_str": null,
        "text": "I've landed 90% my positions and jobs from 'who' I know or who I happen to be referred by, more that from 'what' I know. Your acumen is how\u2026"
    },
    "profile_background_color": "0a090a",
    "listed_count": 7,
    "contributors_enabled": false,
    "screen_name": "triomatt"
}, {
    "id": 14724370,
    "geo_enabled": true,
    "location": "KCMO",
    "verified": false,
    "profile_background_image_url": "http:\/\/a0.twimg.com\/images\/themes\/theme1\/bg.png",
    "is_translator": false,
    "show_all_inline_media": false,
    "follow_request_sent": false,
    "time_zone": "Central Time (US & Canada)",
    "profile_link_color": "0084B4",
    "statuses_count": 516,
    "lang": "en",
    "utc_offset": -21600,
    "profile_image_url_https": "https:\/\/si0.twimg.com\/profile_images\/841576983\/nick_normal.jpg",
    "profile_background_image_url_https": "https:\/\/si0.twimg.com\/images\/themes\/theme1\/bg.png",
    "friends_count": 535,
    "name": "Nick Christus",
    "default_profile_image": false,
    "profile_use_background_image": true,
    "profile_text_color": "333333",
    "favourites_count": 628,
    "protected": false,
    "profile_image_url": "http:\/\/a0.twimg.com\/profile_images\/841576983\/nick_normal.jpg",
    "followers_count": 232,
    "profile_sidebar_border_color": "C0DEED",
    "id_str": "14724370",
    "following": false,
    "description": "Pip, Nicktropoplis, Capt. Amazing, yeah you know me",
    "notifications": false,
    "profile_background_tile": false,
    "default_profile": true,
    "profile_sidebar_fill_color": "DDEEF6",
    "url": "http:\/\/countrycore.com",
    "created_at": "Sat May 10 13:22:13 +0000 2008",
    "status": {
        "geo": null,
        "truncated": false,
        "in_reply_to_user_id_str": null,
        "retweeted": false,
        "coordinates": null,
        "in_reply_to_screen_name": null,
        "place": null,
        "possibly_sensitive": false,
        "contributors": null,
        "id_str": "195583508159270913",
        "in_reply_to_user_id": null,
        "retweet_count": 0,
        "favorited": false,
        "source": "\u003Ca href=\"http:\/\/itunes.apple.com\/us\/app\/twitter\/id409789998?mt=12\" rel=\"nofollow\"\u003ETwitter for Mac\u003C\/a\u003E",
        "in_reply_to_status_id": null,
        "id": 195583508159270913,
        "created_at": "Thu Apr 26 18:41:56 +0000 2012",
        "in_reply_to_status_id_str": null,
        "text": "\u201c@gt: Most interfaces would look 10x better if all the layer styles were turned off.\u201d cf. http:\/\/t.co\/LkmUGMdf @rdio"
    },
    "profile_background_color": "C0DEED",
    "listed_count": 9,
    "contributors_enabled": false,
    "screen_name": "nchristus"
}, {
    "id": 180576932,
    "geo_enabled": false,
    "location": "Kansas City",
    "verified": false,
    "profile_background_image_url": "http:\/\/a0.twimg.com\/images\/themes\/theme9\/bg.gif",
    "is_translator": false,
    "show_all_inline_media": false,
    "follow_request_sent": null,
    "time_zone": "Central Time (US & Canada)",
    "profile_link_color": "c2321b",
    "statuses_count": 524,
    "lang": "en",
    "utc_offset": -21600,
    "profile_image_url_https": "https:\/\/si0.twimg.com\/profile_images\/1403611931\/twitterpic_normal.jpg",
    "profile_background_image_url_https": "https:\/\/si0.twimg.com\/images\/themes\/theme9\/bg.gif",
    "friends_count": 52,
    "name": "Brett Gaynor",
    "default_profile_image": false,
    "profile_use_background_image": true,
    "profile_text_color": "666666",
    "favourites_count": 17,
    "protected": false,
    "profile_image_url": "http:\/\/a0.twimg.com\/profile_images\/1403611931\/twitterpic_normal.jpg",
    "followers_count": 40,
    "profile_sidebar_border_color": "181A1E",
    "id_str": "180576932",
    "following": null,
    "description": "I'm a web designer and photographer; all around creative type. ",
    "notifications": null,
    "profile_background_tile": false,
    "default_profile": false,
    "profile_sidebar_fill_color": "252429",
    "url": null,
    "created_at": "Thu Aug 19 23:53:25 +0000 2010",
    "status": {
        "geo": null,
        "truncated": false,
        "in_reply_to_user_id_str": null,
        "retweeted": false,
        "coordinates": null,
        "in_reply_to_screen_name": null,
        "place": null,
        "possibly_sensitive": false,
        "contributors": null,
        "id_str": "195837547568562176",
        "in_reply_to_user_id": null,
        "retweet_count": 0,
        "favorited": false,
        "source": "\u003Ca href=\"http:\/\/instagr.am\" rel=\"nofollow\"\u003EInstagram\u003C\/a\u003E",
        "in_reply_to_status_id": null,
        "id": 195837547568562176,
        "created_at": "Fri Apr 27 11:31:24 +0000 2012",
        "in_reply_to_status_id_str": null,
        "text": "The cupboards are officially bare. #movingDayEve http:\/\/t.co\/PlgvvoIQ"
    },
    "profile_background_color": "1A1B1F",
    "listed_count": 4,
    "contributors_enabled": false,
    "screen_name": "brettgaynor"
}, {
    "id": 17593121,
    "geo_enabled": false,
    "location": "Kansas City, MO, United States",
    "verified": false,
    "profile_background_image_url": "http:\/\/a0.twimg.com\/profile_background_images\/9261601\/deathP.jpg",
    "is_translator": false,
    "show_all_inline_media": false,
    "follow_request_sent": null,
    "time_zone": "Central Time (US & Canada)",
    "profile_link_color": "262223",
    "statuses_count": 1611,
    "lang": "en",
    "utc_offset": -21600,
    "profile_image_url_https": "https:\/\/si0.twimg.com\/profile_images\/1508631155\/asv6_256_reasonably_small_normal.png",
    "profile_background_image_url_https": "https:\/\/si0.twimg.com\/profile_background_images\/9261601\/deathP.jpg",
    "friends_count": 90,
    "name": "Troy Blank",
    "default_profile_image": false,
    "profile_use_background_image": true,
    "profile_text_color": "262223",
    "favourites_count": 4,
    "protected": false,
    "profile_image_url": "http:\/\/a0.twimg.com\/profile_images\/1508631155\/asv6_256_reasonably_small_normal.png",
    "followers_count": 100,
    "profile_sidebar_border_color": "262223",
    "id_str": "17593121",
    "following": null,
    "description": "Troy makes the things you hate move pretty like with Flash, Processing, Audrino.",
    "notifications": null,
    "profile_background_tile": false,
    "default_profile": false,
    "profile_sidebar_fill_color": "ffffff",
    "url": "http:\/\/www.troyblank.com",
    "created_at": "Mon Nov 24 15:02:21 +0000 2008",
    "status": {
        "geo": null,
        "truncated": false,
        "in_reply_to_user_id_str": null,
        "retweeted": false,
        "coordinates": null,
        "in_reply_to_screen_name": null,
        "place": null,
        "contributors": null,
        "id_str": "197044207473528832",
        "in_reply_to_user_id": null,
        "retweet_count": 0,
        "favorited": false,
        "source": "web",
        "in_reply_to_status_id": null,
        "id": 197044207473528832,
        "created_at": "Mon Apr 30 19:26:14 +0000 2012",
        "in_reply_to_status_id_str": null,
        "text": "I don't understand the new apple gate keeper, i thought that was just what OSx did itself."
    },
    "profile_background_color": "ffffff",
    "listed_count": 7,
    "contributors_enabled": false,
    "screen_name": "troyblank"
}, {
    "id": 237468953,
    "geo_enabled": true,
    "location": "Kansas City",
    "verified": false,
    "profile_background_image_url": "http:\/\/a0.twimg.com\/images\/themes\/theme1\/bg.png",
    "is_translator": false,
    "show_all_inline_media": false,
    "follow_request_sent": null,
    "time_zone": null,
    "profile_link_color": "0084B4",
    "statuses_count": 450,
    "lang": "en",
    "utc_offset": null,
    "profile_image_url_https": "https:\/\/si0.twimg.com\/profile_images\/1787967980\/twitterpic_normal.png",
    "profile_background_image_url_https": "https:\/\/si0.twimg.com\/images\/themes\/theme1\/bg.png",
    "friends_count": 48,
    "name": "Joseph Andaverde",
    "default_profile_image": false,
    "profile_use_background_image": true,
    "profile_text_color": "333333",
    "favourites_count": 13,
    "protected": false,
    "profile_image_url": "http:\/\/a0.twimg.com\/profile_images\/1787967980\/twitterpic_normal.png",
    "followers_count": 57,
    "profile_sidebar_border_color": "C0DEED",
    "id_str": "237468953",
    "following": null,
    "description": "I graduated from KSU in 2009 and now I'm a software developer for Softek Solutions, Inc. in Kansas City. ",
    "notifications": null,
    "profile_background_tile": false,
    "default_profile": true,
    "profile_sidebar_fill_color": "DDEEF6",
    "url": null,
    "created_at": "Wed Jan 12 22:37:51 +0000 2011",
    "status": {
        "geo": null,
        "truncated": true,
        "in_reply_to_user_id_str": null,
        "retweeted": false,
        "coordinates": null,
        "in_reply_to_screen_name": null,
        "place": null,
        "possibly_sensitive": false,
        "retweeted_status": {
            "geo": null,
            "truncated": false,
            "in_reply_to_user_id_str": null,
            "retweeted": false,
            "coordinates": null,
            "in_reply_to_screen_name": null,
            "place": null,
            "possibly_sensitive": false,
            "contributors": null,
            "id_str": "197017634825449472",
            "in_reply_to_user_id": null,
            "retweet_count": 1,
            "favorited": false,
            "source": "\u003Ca href=\"http:\/\/www.hootsuite.com\" rel=\"nofollow\"\u003EHootSuite\u003C\/a\u003E",
            "in_reply_to_status_id": null,
            "id": 197017634825449472,
            "created_at": "Mon Apr 30 17:40:39 +0000 2012",
            "in_reply_to_status_id_str": null,
            "text": "RT @rickusherkcmo: \u201c@benasmith: \"Web 2.0 Is Over, All Hail the Age of Mobile\" http:\/\/t.co\/reaYKqA2\u201d #KC @GoogleinKC #googlefiber"
        },
        "contributors": null,
        "id_str": "197101403448160256",
        "in_reply_to_user_id": null,
        "retweet_count": 1,
        "favorited": false,
        "source": "\u003Ca href=\"http:\/\/itunes.apple.com\/us\/app\/twitter\/id409789998?mt=12\" rel=\"nofollow\"\u003ETwitter for Mac\u003C\/a\u003E",
        "in_reply_to_status_id": null,
        "id": 197101403448160256,
        "created_at": "Mon Apr 30 23:13:31 +0000 2012",
        "in_reply_to_status_id_str": null,
        "text": "RT @GoogleinKC: RT @rickusherkcmo: \u201c@benasmith: \"Web 2.0 Is Over, All Hail the Age of Mobile\" http:\/\/t.co\/reaYKqA2\u201d #KC @GoogleinKC #goo ..."
    },
    "profile_background_color": "C0DEED",
    "listed_count": 1,
    "contributors_enabled": false,
    "screen_name": "joeandaverde"
}, {
    "id": 17874441,
    "geo_enabled": true,
    "location": "Belton, MO (near K.C.)",
    "verified": false,
    "profile_background_image_url": "http:\/\/a0.twimg.com\/images\/themes\/theme14\/bg.gif",
    "is_translator": false,
    "show_all_inline_media": true,
    "follow_request_sent": null,
    "time_zone": "Central Time (US & Canada)",
    "profile_link_color": "009999",
    "statuses_count": 1829,
    "lang": "en",
    "utc_offset": -21600,
    "profile_image_url_https": "https:\/\/si0.twimg.com\/profile_images\/1376860059\/Photo_on_2011-05-31_at_19.52_normal.jpg",
    "profile_background_image_url_https": "https:\/\/si0.twimg.com\/images\/themes\/theme14\/bg.gif",
    "friends_count": 244,
    "name": "Steven Cummings",
    "default_profile_image": false,
    "profile_use_background_image": true,
    "profile_text_color": "333333",
    "favourites_count": 16,
    "protected": false,
    "profile_image_url": "http:\/\/a0.twimg.com\/profile_images\/1376860059\/Photo_on_2011-05-31_at_19.52_normal.jpg",
    "followers_count": 164,
    "profile_sidebar_border_color": "eeeeee",
    "id_str": "17874441",
    "following": null,
    "description": "Python programmer, husband, father of a brood of three, elephant polo restricted free agent.",
    "notifications": null,
    "profile_background_tile": true,
    "default_profile": false,
    "profile_sidebar_fill_color": "efefef",
    "url": null,
    "created_at": "Thu Dec 04 18:48:01 +0000 2008",
    "status": {
        "geo": null,
        "truncated": false,
        "in_reply_to_user_id_str": null,
        "retweeted": false,
        "coordinates": null,
        "in_reply_to_screen_name": null,
        "place": null,
        "possibly_sensitive": false,
        "retweeted_status": {
            "geo": null,
            "truncated": false,
            "in_reply_to_user_id_str": null,
            "retweeted": false,
            "coordinates": null,
            "in_reply_to_screen_name": null,
            "place": null,
            "possibly_sensitive": false,
            "contributors": null,
            "id_str": "195976133123117056",
            "in_reply_to_user_id": null,
            "retweet_count": 17,
            "favorited": false,
            "source": "\u003Ca href=\"http:\/\/news.ycombinator.com\/\" rel=\"nofollow\"\u003EHacker News Bot\u003C\/a\u003E",
            "in_reply_to_status_id": null,
            "id": 195976133123117056,
            "created_at": "Fri Apr 27 20:42:05 +0000 2012",
            "in_reply_to_status_id_str": null,
            "text": "Incredibox - Background music for programming.... http:\/\/t.co\/wRrRGm8L"
        },
        "contributors": null,
        "id_str": "195979452117823490",
        "in_reply_to_user_id": null,
        "retweet_count": 17,
        "favorited": false,
        "source": "web",
        "in_reply_to_status_id": null,
        "id": 195979452117823490,
        "created_at": "Fri Apr 27 20:55:17 +0000 2012",
        "in_reply_to_status_id_str": null,
        "text": "RT @hackernewsbot: Incredibox - Background music for programming.... http:\/\/t.co\/wRrRGm8L"
    },
    "profile_background_color": "131516",
    "listed_count": 16,
    "contributors_enabled": false,
    "screen_name": "estebistec"
}, {
    "id": 456682136,
    "geo_enabled": false,
    "location": "Kansas City Metro, USA",
    "verified": false,
    "profile_background_image_url": "http:\/\/a0.twimg.com\/images\/themes\/theme4\/bg.gif",
    "is_translator": false,
    "show_all_inline_media": false,
    "follow_request_sent": false,
    "time_zone": "Central Time (US & Canada)",
    "profile_link_color": "0099B9",
    "statuses_count": 15,
    "lang": "en",
    "utc_offset": -21600,
    "profile_image_url_https": "https:\/\/si0.twimg.com\/profile_images\/1737224412\/06-beautiful_mountains_small_normal.JPG",
    "profile_background_image_url_https": "https:\/\/si0.twimg.com\/images\/themes\/theme4\/bg.gif",
    "friends_count": 31,
    "name": "Agent[J]eremySellars",
    "default_profile_image": false,
    "profile_use_background_image": true,
    "profile_text_color": "3C3940",
    "favourites_count": 1,
    "protected": false,
    "profile_image_url": "http:\/\/a0.twimg.com\/profile_images\/1737224412\/06-beautiful_mountains_small_normal.JPG",
    "followers_count": 9,
    "profile_sidebar_border_color": "5ED4DC",
    "id_str": "456682136",
    "following": false,
    "description": "These tweets are more software-development-related.  I lean toward c#\/.net. I love my wife,girl&boy. Since childhood I've written fun software.",
    "notifications": false,
    "profile_background_tile": false,
    "default_profile": false,
    "profile_sidebar_fill_color": "95E8EC",
    "url": "http:\/\/stackoverflow.com\/users\/787893\/agent-j",
    "created_at": "Fri Jan 06 14:47:41 +0000 2012",
    "status": {
        "geo": null,
        "truncated": false,
        "in_reply_to_user_id_str": null,
        "retweeted": false,
        "coordinates": null,
        "in_reply_to_screen_name": null,
        "place": null,
        "contributors": null,
        "id_str": "197000779553456129",
        "in_reply_to_user_id": null,
        "retweet_count": 0,
        "favorited": false,
        "source": "\u003Ca href=\"http:\/\/www.tweetcaster.com\" rel=\"nofollow\"\u003ETweetCaster for Android\u003C\/a\u003E",
        "in_reply_to_status_id": null,
        "id": 197000779553456129,
        "created_at": "Mon Apr 30 16:33:40 +0000 2012",
        "in_reply_to_status_id_str": null,
        "text": "Today marks my 10th anniversary at @softekinc.  Five of us can say they've been here 10y.  Wow!  What an exciting future ahead!"
    },
    "profile_background_color": "0099B9",
    "listed_count": 0,
    "contributors_enabled": false,
    "screen_name": "agentJsellars"
}, {
    "id": 11578522,
    "geo_enabled": true,
    "location": "Kansas City, MO",
    "verified": false,
    "profile_background_image_url": "http:\/\/a0.twimg.com\/images\/themes\/theme9\/bg.gif",
    "is_translator": false,
    "show_all_inline_media": false,
    "follow_request_sent": null,
    "time_zone": "Central Time (US & Canada)",
    "profile_link_color": "2FC2EF",
    "statuses_count": 232,
    "lang": "en",
    "utc_offset": -21600,
    "profile_image_url_https": "https:\/\/si0.twimg.com\/profile_images\/1865682621\/profile_normal.jpg",
    "profile_background_image_url_https": "https:\/\/si0.twimg.com\/images\/themes\/theme9\/bg.gif",
    "friends_count": 482,
    "name": "Casey Justus",
    "default_profile_image": false,
    "profile_use_background_image": true,
    "profile_text_color": "666666",
    "favourites_count": 10,
    "protected": false,
    "profile_image_url": "http:\/\/a0.twimg.com\/profile_images\/1865682621\/profile_normal.jpg",
    "followers_count": 155,
    "profile_sidebar_border_color": "181A1E",
    "id_str": "11578522",
    "following": null,
    "description": "Javascript Programmer for @VML(the agency), homebrewer, enthusiast",
    "notifications": null,
    "profile_background_tile": false,
    "default_profile": false,
    "profile_sidebar_fill_color": "252429",
    "url": "http:\/\/caseyjustus.com",
    "created_at": "Thu Dec 27 20:30:17 +0000 2007",
    "status": {
        "geo": null,
        "truncated": false,
        "in_reply_to_user_id_str": null,
        "retweeted": false,
        "coordinates": null,
        "in_reply_to_screen_name": null,
        "place": null,
        "possibly_sensitive": false,
        "contributors": null,
        "id_str": "197397428629012481",
        "in_reply_to_user_id": null,
        "retweet_count": 0,
        "favorited": false,
        "source": "\u003Ca href=\"http:\/\/bit.ly\" rel=\"nofollow\"\u003Ebitly\u003C\/a\u003E",
        "in_reply_to_status_id": null,
        "id": 197397428629012481,
        "created_at": "Tue May 01 18:49:49 +0000 2012",
        "in_reply_to_status_id_str": null,
        "text": "Agencies Open Brand Doors to Tech Startups | Adweek http:\/\/t.co\/9njq302r"
    },
    "profile_background_color": "1A1B1F",
    "listed_count": 5,
    "contributors_enabled": false,
    "screen_name": "caseyjustus"
}];